### ISSUE TITLE
Once initialized we cannot move to slide 0 from the code

### ISSUE THREAD

**Issue by akash-motwani** [sheikalthaf/ngx-carousel#58] opened 2017-11-24 09:51 UTC
As in onChanges we check if this.moveToSlide has some value then only it calls the function that changes the slide number to the number we specified. But suppose if the move to slide number 0 then this.moveToSlide would be 0 and hence it wont call the function to change the slide number to 0.

**Comment by sheikalthaf** [comment] 2017-11-24 19:38
Duplicate of #55

**Comment by sheikalthaf** [comment] 2017-11-26 07:43
Fixed the bug in Build v1.3.4
Thanks

**Comment by akash-motwani** [comment] 2017-11-26 13:11
Thank you so much. 🙂

**Closed** 2017-11-28 04:21 UTC
